config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/email'

  resources :events
  resources :users, path: "employees"
  root 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :caller, class_name: "User", foreign_key: "caller_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  validates_presence_of :data, :duration, :topic

  mount_uploader :audio, AudioUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :validatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable
  
  TYPES_OFF = [:local, :foreigns, :remote]
  #enum type_of: TYPES_OFF

  belongs_to :manager , class_name: "User", foreign_key: "manager_id", required: false
  validates_presence_of :name, :email
  validates :email, uniqueness: { case_sensitive: false }

  has_many :employees, class_name: "User", foreign_key: "manager_id"
  
  def is_manager?
    self.employees.any?
  end

  def self.all_less_me(user)
    User.where("id != ?", user.id).order(:name)
  end

  def self.all_managers
    ids = User.select("manager_id").where("manager_id IS NOT NULL")
    User.where("id IN (?)",ids)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |employee|
        csv << employee.attributes.values_at(*column_names)
      end
    end
  end

  def self.send_report user
    SystemMailer.send_report(user).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.caller = current_user
    @receivers = User.all_less_me(current_user)
  end

  # GET /events/1/edit
  def edit
    @receivers = User.all_less_me(current_user)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge(caller_id: current_user.id))

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        @receivers = User.all_less_me(current_user)
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:data, :duration, :topic, :caller_id, :receiver_id,:audio)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!,only: [:index]
  
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @users = User.all
  end

  def email
    User.send_report(current_user)
    redirect_to reports_index_path, notice: 'Report was successfully send.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv }
      format.pdf {render pdf: "index", dispoistion: :attachment}
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @user = User.new
    @managers = User.all
  end

  # GET /employees/1/edit
  def edit
    @managers = User.all_less_me(@user)
  end

  # POST /employees
  # POST /employees.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|      
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :type_of,:manager_id,:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event, html: {:class =>"form-horizontal"} do |f|
  = f.error_notification

  .form-inputs
    = f.input :data,required: true
    = f.input :duration, required: true,hint: "Numeros de minutos"
    = f.input :topic, required: true
    = f.association :receiver ,collection: @receivers,:value_method => :id,include_blank: true, required: true
    = f.input :audio, multiple: false 
  %hr
  .form-actions
    = f.button :submit

app/views/events/edit.html.haml
%h1 Editing Registration Call

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table.table
  %thead
    %tr
      %th Data
      %th Duration
      %th Topic
      %th Caller
      %th Receiver
      %th Audio
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.data
        %td= event.duration
        %td= event.topic
        %td
          = link_to event.caller.name, event.caller
        %td
          = link_to event.receiver.name, event.receiver
        %td
          %audio{:controls => ""}
            %source{:src => "#{event.audio_url}", :type => "audio/mpeg"}
              Your browser does not support the audio element.
        %td
          = link_to 'Show', event
          = link_to 'Edit', edit_event_path(event)
          = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

%hr

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New Regsitration Call

= render 'form'

%br
= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%dl.dl-horizontal
  %dt Data:
  %dd= @event.data
  %dt Duration:
  %dd= @event.duration
  %dt Topic
  %dd= @event.topic
  %dt Caller:
  %dd
    = link_to @event.caller.name, @event.caller
  %dt Receiver:
  %dd
    = link_to @event.receiver.name, @event.receiver
  - if @event.audio?
    %dt Audio:
    %dd
      %audio{:controls => ""}
        %source{:src => "#{@event.audio_url}", :type => "audio/mpeg"}
          Your browser does not support the audio element.

%hr

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/home/index.html.haml
.jumbotron
  .container
    %h1 Hello, world!
    %p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
    - unless current_user
      %p      
        = link_to "Registration", new_user_registration_path, class: "btn btn-primary btn-lg"

app/views/layouts/_navigator.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header.navbar-left
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Upstack Employees
    
    - if current_user
      #navbar.navbar-collapse.collapse.navbar-left
        %ul.nav.navbar-nav
          %li
            = link_to "Employees", users_path
          %li
            = link_to "Calls", events_path
          %li
            = link_to "Reports", reports_index_path    
    #navbar.navbar-collapse.collapse.navbar-right
      %ul.nav.navbar-nav
        %li
          - if current_user            
            = link_to destroy_user_session_path,:method=>'delete' do
              = current_user.name
              %span.glyphicon.glyphicon-off
          - else
            = link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UpstackApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    = render "layouts/navigator"
    .container
      .row
        .col-md-12
          = yield

app/views/reports/_index.html.haml
%h1 Employees Report

%table
  %thead
    %tr
      %th Name
      %th Type of
      %th Manager
      %th

  %tbody
    - users.each do |employee|
      %tr
        %td= employee.name
        %td= employee.type_of
        %td
          - if employee.manager
            = employee.manager.name
         

app/views/reports/index.html.haml
%p#notice= notice

= render :partial => "reports/index", :locals => {users: @users}
%hr
= link_to 'Email', reports_email_path

app/views/users/_form.html.haml
= simple_form_for @user, html: {:class =>"form-horizontal"} do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email, required: true
    = f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length)
    = f.input :type_of, collection: User::TYPES_OFF,include_blank: false, required: false
    = f.association :manager ,collection: @managers,:value_method => :id,include_blank: true, required: false
  %hr
  .form-actions
    = f.button :submit

app/views/users/_search.html.haml
%h1 Search Employee

= search_form_for @q,class: "form-inline" do |f|
  .form-group
    = f.label :name
    = f.search_field :name_cont,class: "form-control"
  .form-group
    = f.label :type_of
    = f.search_field :type_of_eq, class: "form-control"
  
  = f.submit "Search", class: "btn btn-default"
%hr

app/views/users/edit.html.haml
%h1 Editing employee

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- if current_user.is_manager?
  = render "search"


%h1 Listing employees

%table.table
  %thead
    %tr
      %th Name
      %th Type of
      %th Manager
      %th

  %tbody
    - @users.each do |employee|
      %tr
        %td= employee.name
        %td= employee.type_of
        %td
          - if employee.manager
            = link_to employee.manager.name, employee.manager
        %td
          = link_to 'Show', employee
          = link_to 'Edit', edit_user_path(employee)
          = link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }

%hr

= link_to 'New Employee', new_user_path

= search_form_for @q,format: :csv do |f|
  .hidden
    = f.label :name
    = f.search_field :name_cont
    = f.label :type_of
    = f.search_field :type_of_eq
  = f.submit "Down Load CVS", class: "btn btn-default"

= search_form_for @q,format: :pdf do |f|
  .hidden
    = f.label :name
    = f.search_field :name_cont
    = f.label :type_of
    = f.search_field :type_of_eq
  = f.submit "Down Load PDF", class: "btn btn-default"

app/views/users/index.pdf.haml
%h1 Listing employees

%table.table
  %thead
    %tr
      %th Name
      %th Type of
      %th Manager

  %tbody
    - @users.each do |employee|
      %tr
        %td= employee.name
        %td= employee.type_of
        %td
          - if employee.manager
            = link_to employee.manager.name, employee.manager

app/views/users/new.html.haml
%h1 New employee
%hr
= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%dl.dl-horizontal
  %dt Name:
  %dd= @user.name
  %dt Email:
  %dd= @user.email
  - if @user.manager
    %dt Manager:
    %dd
      = link_to @user.manager.name, @user.manager


  %dt Type of:
  %dd= @user.type_of
  - if @user.employees.any?
    %dt Employees:
    %dd
      - @user.employees.each do |employee|
        %span.label.label-info
          = employee.name
%hr
= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path